package com.charmingwong.cwimage.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.charmingwong.cwimage.search.model.SearchRecord;
import com.charmingwong.cwimage.imagelibrary.CollectionImage;
import com.charmingwong.cwimage.imagelibrary.CollectionTag;
import com.charmingwong.cwimage.imagelibrary.DownloadImage;

import com.charmingwong.cwimage.dao.SearchRecordDao;
import com.charmingwong.cwimage.dao.CollectionImageDao;
import com.charmingwong.cwimage.dao.CollectionTagDao;
import com.charmingwong.cwimage.dao.DownloadImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchRecordDaoConfig;
    private final DaoConfig collectionImageDaoConfig;
    private final DaoConfig collectionTagDaoConfig;
    private final DaoConfig downloadImageDaoConfig;

    private final SearchRecordDao searchRecordDao;
    private final CollectionImageDao collectionImageDao;
    private final CollectionTagDao collectionTagDao;
    private final DownloadImageDao downloadImageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchRecordDaoConfig = daoConfigMap.get(SearchRecordDao.class).clone();
        searchRecordDaoConfig.initIdentityScope(type);

        collectionImageDaoConfig = daoConfigMap.get(CollectionImageDao.class).clone();
        collectionImageDaoConfig.initIdentityScope(type);

        collectionTagDaoConfig = daoConfigMap.get(CollectionTagDao.class).clone();
        collectionTagDaoConfig.initIdentityScope(type);

        downloadImageDaoConfig = daoConfigMap.get(DownloadImageDao.class).clone();
        downloadImageDaoConfig.initIdentityScope(type);

        searchRecordDao = new SearchRecordDao(searchRecordDaoConfig, this);
        collectionImageDao = new CollectionImageDao(collectionImageDaoConfig, this);
        collectionTagDao = new CollectionTagDao(collectionTagDaoConfig, this);
        downloadImageDao = new DownloadImageDao(downloadImageDaoConfig, this);

        registerDao(SearchRecord.class, searchRecordDao);
        registerDao(CollectionImage.class, collectionImageDao);
        registerDao(CollectionTag.class, collectionTagDao);
        registerDao(DownloadImage.class, downloadImageDao);
    }
    
    public void clear() {
        searchRecordDaoConfig.clearIdentityScope();
        collectionImageDaoConfig.clearIdentityScope();
        collectionTagDaoConfig.clearIdentityScope();
        downloadImageDaoConfig.clearIdentityScope();
    }

    public SearchRecordDao getSearchRecordDao() {
        return searchRecordDao;
    }

    public CollectionImageDao getCollectionImageDao() {
        return collectionImageDao;
    }

    public CollectionTagDao getCollectionTagDao() {
        return collectionTagDao;
    }

    public DownloadImageDao getDownloadImageDao() {
        return downloadImageDao;
    }

}
